[package]
name = "rocket-model-codegen"
version = "0.1.0"
authors = ["Linas NikiperaviÄius <linas@linasdev.com>"]
license = "MIT"
description = "Macros for generating model structs"
repository = "https://github.com/linasdev/rocket-model-codegen"
edition = "2018"

[dependencies]
